### ISSUE TITLE
Support of overriding CC (REAL_CC & LLVM_CC)

### ISSUE THREAD

**Issue by jirislaby** [Linhos13/dtlu#5]
I should be able to set something similar to stcc's REAL_CC like REAL_CC=gcc-7 which is used as a real compiler. Another one should be e.g. LLVM_CC=clang-4.6 to be used as the llvm emitter (the one which receives -emit-llvm and produces the llvm bitcode).

The defaults are of course `cc` (usually current version of gcc) and `clang` (current version of clang).

**Comment by Linhos13** [comment]
Added env variables REAL_CC and LLVM_CC
